### PR TITLE
[W.I.P] Initial testing framework

### PR DESCRIPTION
**Pull request by code-R**

### CODE REVIEW

**Comment by code-R** [comment]
I am planning to add tox and requirements and test-requirements as well. If any suggestions please let me know. I need to add test-requirements and requirements file as well.

**Comment by bryan-strassner** [comment]
Hi, the submission path for shipyard code has moved to gerrithub:  https://review.gerrithub.io/#/admin/projects/att-comdev/shipyard
Apologies that the documentation here is not yet updated to indicate as such.

**Comment by code-R** [comment]
@bryan-strassner thanks, I will close this pull request and push it gerrithub.. Any suggestion about which testing framework to be used? I mean if you guys want to use nose or anything specific or pytest is fine ? since I would like to add more tests and any feedback would be appreciated.

**Comment by code-R** [comment]
moved to gerrithub https://review.gerrithub.io/#/c/373959/

**Comment by bryan-strassner** [comment]
pytest is fine!

**Comment by bryan-strassner** [comment]
pytest is good.

**Pull request closed without merging**
